# Install and config snap
- name: Install the latest version packages snapd
  dnf:
    name:
      - snapd
    state: latest
    
- name: Create a symbolic link to snap
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
# End Snap