---
# tasks file for helm

# Helm
- name: return motd to registered var
  shell: |
    curl -s https://api.github.com/repos/helm/helm/releases/latest | grep tag_name | cut -d: -f2 | tr -d \"\, | awk '{$1=$1};1'
  register: HELM_VER
  ignore_errors: yes
- set_fact:
    HELM_VER={{ HELM_VER.stdout }}
- name: Extract helm*.tar.gz into /tmp
  unarchive:
    src: https://get.helm.sh/helm-{{ HELM_VER }}-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes
- name: Move helm exec file to path
  copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    mode: +x