# Kubectl
- name: Add kubernetes repositories
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    repo_gpgcheck: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gp
- name: Install kubectl package
  dnf:
    name: kubectl
    state: latest
    update_cache: yes
# End kubectl